# Spring boot application
spring:
  application:
    name: yfshop-service-content-provider
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.126:3307/myshop?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8502

# MyBatis Config properties
mybatis:
  type-aliases-package: com.yifeng.yfshop.commons.domain
  mapper-locations: classpath:mapper/*.xml

# Services Versions
services:
  versions:
    content:
      v1: 1.0.0

# Dubbo Config properties
dubbo:
  ## Base packages to scan Dubbo Componentï¼š@com.alibaba.dubbo.config.annotation.Service
  scan:
    basePackages: com.yifeng.yfshop.service.content.provider.api.impl
  ## ApplicationConfig Bean
  application:
    id: yfshop-service-content-provider
    name: yfshop-service-content-provider
    qos-port: 22223
    qos-enable: true
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 20882
    status: server
    serialization: kryo
  ## RegistryConfig Bean
  registry:
    id: zookeeper
    address: zookeeper://192.168.1.196:2181?backup=192.168.1.196:2182,192.168.1.196:2183

# Enables Dubbo All Endpoints
management:
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true
  # Dubbo Health
  health:
    dubbo:
      status:
        ## StatusChecker Name defaults (default : "memory", "load" )
        defaults: memory
        ## StatusChecker Name extras (default : empty )
        extras: load,threadpool


logging:
  level.com.yifeng.yfshop.commons.mapper: DEBUG